import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/main.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={`${styles.pageSection}, ${styles.headSection}`}>
          <div className={styles.avatarSection}>
            <img
              className={styles.avatarImage}
              src="https://avatars.githubusercontent.com/u/7761715?v=4"
            />

            <p className={styles.avatarText}>
              Hey I'm Noah! I'm a software engineer from Victoria, BC.
            </p>
          </div>
          <div className={styles.sectionLinks}>
            <button className={styles.sectionLink}>Projects</button>
            <button className={styles.sectionLink}>Photos</button>
            <button className={styles.sectionLink}>About</button>
          </div>
        </div>
        <div className={`${styles.pageSection}, ${styles.headSection}`}>
          <h1>Projects</h1>
        </div>
        <div className={`${styles.pageSection}, ${styles.headSection}`}>
          <h1>Photos</h1>
        </div>
        <div className={`${styles.pageSection}, ${styles.headSection}`}>
          <h1>About</h1>
        </div>
      </main>
    </div>
  );
};

export default Home;
